apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-news-demo
  labels:
    app: golang-news-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-news-demo
  template:
    metadata:
      labels:
        app: golang-news-demo
    spec:
      containers:
      - name: golang-news-demo
        image: <YOUR_DOCKER_IMAGE_NAME>:<YOUR_TAG>  # Replace with your image name and tag
        ports:
        - containerPort: 80  # Adjust if your application uses a different port
        env: # If you have any environment variables, list them here
        - name: PORT
          value: 3000
        - name: NEWS_API_KEY
          value: "value2"
---

