apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-golang-news
  labels:
    app: oci-golang-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oci-golang-news
  template:
    metadata:
      labels:
        app: oci-golang-news
    spec:
      containers:
      - name: oci-golang-news
        image: <YOUR_DOCKER_IMAGE_NAME>:<YOUR_TAG>  # Replace with your image name and tag
        ports:
        - containerPort: 80  # Adjust if your application uses a different port
        env: # If you have any environment variables, list them here
        - name: MY_VAR1
          value: "value1"
        - name: MY_VAR2
          value: "value2"
---
apiVersion: v1
kind: Service
metadata:
  name: oci-golang-news-service
spec:
  selector:
    app: oci-golang-news
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This will provision a cloud load balancer, change if needed
